name: CI

on: [push]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: 'us-west-1'
  IMAGE_REPOSITORY: micahlmartin/github-deployment-test

jobs:

  ci:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      
      # - name: Set commit version info
      #   run: |
      #     echo "::set-env name=VERSION::sha-$(echo "$GITHUB_SHA" | cut -c1-7)"

      # - name: Set PR version info
      #   if: github.event_name == 'pull_request'
      #   run: |
      #     echo "::set-env name=VERSION::pr-${{ github.event.pull_request.number }}"
      
      # - name: Set build info
      #   run: |
      #     echo "::set-env name=IMAGE::${IMAGE_REPOSITORY}:${VERSION}"

      # - uses: docker/build-push-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
      #     repository: ${{ env.IMAGE_REPOSITORY }}
      #     tag_with_ref: true
      #     tag_with_sha: true

      # - name: Fetch assets from container
      #   run: |
      #     CONTAINER=$(docker create ${IMAGE_REPOSITORY}:${VERSION})
      #     docker cp $CONTAINER:/srv/build ./assets
      #     ls -la ./assets

      # - name: Upload to S3
      #   if: github.ref == 'refs/heads/master'
      #   uses: jakejarvis/s3-sync-action@master
      #   with:
      #     args: --acl public-read --follow-symlinks --delete
      #   env:
      #     AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_STAGING }}
      #     SOURCE_DIR: ./assets
