name: CI

on: [push]


jobs:

  ci:
    runs-on: ubuntu-latest

    steps:

      - name: debug
        run: |
          echo "${{ toJson(github) }}"

      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set release version info
        if: github.event_name == 'release'
        run: |
          echo "::set-env name=VERSION::${{ github.event.release.tag_name }}"
      
      - name: Set commit version info
        if: github.event_name == 'push'
        run: |
          echo "::set-env name=VERSION::$(echo "$GITHUB_SHA" | cut -c1-7)"

      - name: Set PR version info
        if: github.event_name == 'pull_request'
        run: |
          echo "::set-env name=VERSION::pr-${{ github.event.pull_request.number }}"
      
      - name: Set build info
        run: |
          echo "::set-env name=IMAGE::${IMAGE_REPOSITORY}:${VERSION}"

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: micahlmartin/github-deployment-test
          tag_with_ref: true
          tag_with_sha: true

      - name: Deploy to QA
        if: github.ref == 'refs/heads/master'
        uses: elgohr/Github-Hub-Action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: api -X POST /repos/micahlmartin/github-deployment-test/deployments -F ref=master -F environment=qa

