name: Deploy

on: [deployment]

env:
  IMAGE_REPOSITORY: micahlmartin/github-deployment-test

jobs:

  ci:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        with:
          persist-credentials: false
    
      - name: debug
        run:
          echo "${{ toJson(github) }}"

      - name: Update deployment status
        run: |
          curl -X POST \
            --url ${{ github.event.deployment.statuses_url }} \
            -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            -H 'content-type: application/json' \
            -d "{ \
                  \"environment\": \"${{ github.event.deployment.environment }}\", \
                  \"state\": \"success\", \
                  \"description\": \"Deployment finished successfully.\" \
                }"

      # - name: Set release version info
      #   if: github.event_name == 'release'
      #   run: |
      #     echo "::set-env name=VERSION::${{ github.event.release.tag_name }}"
      
      # - name: Set commit version info
      #   if: github.event_name == 'push'
      #   run: |
      #     echo "::set-env name=VERSION::$(echo "$GITHUB_SHA" | cut -c1-7)"

      # - name: Set PR version info
      #   if: github.event_name == 'pull_request'
      #   run: |
      #     echo "::set-env name=VERSION::pr-${{ github.event.pull_request.number }}"
      
      # - name: Set build info
      #   run: |
      #     echo "::set-env name=IMAGE::${IMAGE_REPOSITORY}:${VERSION}"

      # - name: Build docker container
      #   run: |
      #     docker build -t ${IMAGE} .
