name: Deploy

on: [deployment]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: 'us-west-1'
  AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_PRODUCTION }}
  IMAGE_REPOSITORY: micahlmartin/github-deployment-test

jobs:
  
  deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set environment
        run: |
          echo "::set-env name=VERSION::sha-$(echo "${{ github.event.deployment.sha }}" | cut -c1-7)"

      - name: Create a Release
        uses: elgohr/Github-Hub-Action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: api -X POST ${{ github.event.deployment.statuses_url }} -F environment=${{ github.event.deployment.environment }} -F state=in_progress -F description="Uploading assets to S3 bucket."
